#!/bin/sh

prefix="/usr"
xinitdir="/etc/X11/xinit"
xrdb="xrdb"
xmodmap="xmodmap"

userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="$xinitdir/.Xresources"
sysmodmap="$xinitdir/.Xmodmap"

if [ -f "$sysresources" ]; then
    if [ -x /usr/bin/cpp ]; then
        "$xrdb" -merge "$sysresources"
    else
        "$xrdb" -nocpp -merge "$sysresources"
    fi
fi

if [ -f "$sysmodmap" ]; then
    "$xmodmap" "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ]; then
        "$xrdb" -merge "$userresources"
    else
        "$xrdb" -nocpp -merge "$userresources"
    fi
fi

if [ -f "$usermodmap" ]; then
    "$xmodmap" "$usermodmap"
fi

echo "xinitrc: starting session"
if [ -x /usr/bin/startplasma-manual.sh ]; then
    echo "xinitrc: exec startplasma-manual.sh"
    exec /usr/bin/startplasma-manual.sh
fi

echo "xinitrc: fallback sh"
exec sh
