use crate::systemcall::numbers::SyscallNumber;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LinuxSyscallTestKind {
    Unit,
    Integration,
    CoverageGap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LinuxSyscallCoverage {
    pub number: SyscallNumber,
    pub kind: LinuxSyscallTestKind,
    pub test: &'static str,
}

pub const KNOWN_LINUX_SYSCALL_COVERAGE_GAPS: usize = 203;

macro_rules! syscall_coverage {
    (
        unit {
            $($unit_number:ident => $unit_test:literal,)*
        }
        gap {
            $($gap_number:ident,)*
        }
    ) => {
        &[
            $(
                LinuxSyscallCoverage {
                    number: SyscallNumber::$unit_number,
                    kind: LinuxSyscallTestKind::Unit,
                    test: $unit_test,
                },
            )*
            $(
                LinuxSyscallCoverage {
                    number: SyscallNumber::$gap_number,
                    kind: LinuxSyscallTestKind::CoverageGap,
                    test: "needs Linux semantics behavior test",
                },
            )*
        ]
    };
}

pub const LINUX_SYSCALL_SEMANTICS_COVERAGE: &[LinuxSyscallCoverage] = syscall_coverage!(
    unit {
        Getpid => "process_identity_syscalls_match_current_linux_task_state",
        Getppid => "process_identity_syscalls_match_current_linux_task_state",
        Getpgrp => "process_identity_syscalls_match_current_linux_task_state",
        Getpgid => "process_group_syscalls_follow_linux_pid_zero_and_esrch_rules",
        Setpgid => "process_group_syscalls_follow_linux_pid_zero_and_esrch_rules",
        Getuid => "credential_getters_return_current_linux_ids",
        Getgid => "credential_getters_return_current_linux_ids",
        Geteuid => "credential_getters_return_current_linux_ids",
        Getegid => "credential_getters_return_current_linux_ids",
        Setuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setgid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setreuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setregid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setresuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setresgid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setfsuid => "fsuid_fsgid_syscalls_return_previous_ids_and_update_state",
        Setfsgid => "fsuid_fsgid_syscalls_return_previous_ids_and_update_state",
        Getgroups => "group_syscalls_validate_linux_size_rules",
        Setgroups => "group_syscalls_validate_linux_size_rules",
        ClockGetres => "clock_getres_accepts_null_for_valid_clocks_and_rejects_bad_clock_ids",
        SchedYield => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Madvise => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Getpriority => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Setpriority => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        IoprioSet => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        IoprioGet => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetscheduler => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetPriorityMax => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetPriorityMin => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Iopl => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Ioperm => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
    }
    gap {
    Read,
    Write,
    OpenAt,
    Open,
    Close,
    Poll,
    Fstat,
    Lseek,
    Mmap,
    Mprotect,
    Munmap,
    Brk,
    RtSigaction,
    RtSigprocmask,
    RtSigpending,
    RtSigtimedwait,
    RtSigqueueinfo,
    RtSigreturn,
    Ioctl,
    Pread64,
    Pwrite64,
    Writev,
    Access,
    Pipe,
    Mremap,
    Msync,
    Mincore,
    Shmget,
    Shmat,
    Shmctl,
    Dup,
    Dup2,
    Pause,
    Nanosleep,
    Setitimer,
    Sendfile,
    Socket,
    Connect,
    Accept,
    Accept4,
    Sendmsg,
    Sendmmsg,
    Sendto,
    Recvfrom,
    Recvmsg,
    Shutdown,
    Bind,
    Listen,
    Getsockname,
    Getpeername,
    Socketpair,
    Setsockopt,
    Getsockopt,
    Clone,
    Fork,
    Execve,
    Exit,
    Wait4,
    Alarm,
    Kill,
    Uname,
    Umask,
    Ptrace,
    Shmdt,
    Capget,
    Capset,
    Gettimeofday,
    Getrusage,
    Settimeofday,
    Reboot,
    Sethostname,
    Sysinfo,
    Getresuid,
    Getresgid,
    Fcntl,
    Flock,
    Fsync,
    Fdatasync,
    Ftruncate,
    Getdents,
    Prctl,
    Getdents64,
    Getcwd,
    Chdir,
    Chroot,
    Fchdir,
    Rename,
    Mkdir,
    Rmdir,
    Link,
    Unlink,
    Symlink,
    Readlink,
    Chmod,
    Fchmod,
    Chown,
    Fchown,
    Getsid,
    Setsid,
    Sigaltstack,
    Statfs,
    Fstatfs,
    ArchPrctl,
    Gettid,
    Setxattr,
    Lsetxattr,
    Fsetxattr,
    Getxattr,
    Lgetxattr,
    Fgetxattr,
    Listxattr,
    Llistxattr,
    Flistxattr,
    Removexattr,
    Lremovexattr,
    Fremovexattr,
    SetTidAddress,
    Time,
    Futex,
    SchedSetscheduler,
    SchedSetaffinity,
    SchedGetaffinity,
    Fadvise64,
    InotifyInit,
    InotifyAddWatch,
    InotifyRmWatch,
    Waitid,
    AddKey,
    Keyctl,
    EpollWait,
    EpollCtl,
    Tgkill,
    ClockSettime,
    ClockGettime,
    ClockNanosleep,
    MkdirAt,
    Mknodat,
    Fchownat,
    Newfstatat,
    UnlinkAt,
    RenameAt,
    LinkAt,
    SymlinkAt,
    ReadlinkAt,
    Faccessat,
    Pselect6,
    Ppoll,
    Unshare,
    SetRobustList,
    Utimensat,
    EpollPwait,
    TimerfdCreate,
    Eventfd,
    Fallocate,
    TimerfdSettime,
    TimerfdGettime,
    Signalfd4,
    Eventfd2,
    Pipe2,
    Dup3,
    InotifyInit1,
    EpollCreate1,
    Prlimit64,
    NameToHandleAt,
    Setns,
    Kcmp,
    MemfdCreate,
    SchedSetparam,
    SchedGetparam,
    SchedRrGetInterval,
    Setrlimit,
    Sync,
    Mount,
    Umount2,
    RenameAt2,
    TimerCreate,
    TimerSettime,
    TimerGettime,
    TimerGetoverrun,
    TimerDelete,
    Vhangup,
    ExitGroup,
    Faccessat2,
    Getrandom,
    Bpf,
    CopyFileRange,
    Splice,
    Statx,
    Rseq,
    PidfdSendSignal,
    Fchmodat,
    OpenTree,
    MoveMount,
    Fsopen,
    Fsconfig,
    Fsmount,
    PidfdOpen,
    Clone3,
    CloseRange,
    RtSigsuspend,
    EpollPwait2,
    MountSetattr,
    Fchmodat2,
    }
);
