use crate::systemcall::numbers::SyscallNumber;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LinuxSyscallTestKind {
    Unit,
    Integration,
    CoverageGap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LinuxSyscallCoverage {
    pub number: SyscallNumber,
    pub kind: LinuxSyscallTestKind,
    pub test: &'static str,
}

pub const KNOWN_LINUX_SYSCALL_COVERAGE_GAPS: usize = 0;

macro_rules! syscall_coverage {
    (
        unit {
            $($unit_number:ident => $unit_test:literal,)*
        }
        gap {
            $($gap_number:ident,)*
        }
    ) => {
        &[
            $(
                LinuxSyscallCoverage {
                    number: SyscallNumber::$unit_number,
                    kind: LinuxSyscallTestKind::Unit,
                    test: $unit_test,
                },
            )*
            $(
                LinuxSyscallCoverage {
                    number: SyscallNumber::$gap_number,
                    kind: LinuxSyscallTestKind::CoverageGap,
                    test: "needs Linux semantics behavior test",
                },
            )*
        ]
    };
}

pub const LINUX_SYSCALL_SEMANTICS_COVERAGE: &[LinuxSyscallCoverage] = syscall_coverage!(
    unit {
        Getpid => "process_identity_syscalls_match_current_linux_task_state",
        Getppid => "process_identity_syscalls_match_current_linux_task_state",
        Getpgrp => "process_identity_syscalls_match_current_linux_task_state",
        Getpgid => "process_group_syscalls_follow_linux_pid_zero_and_esrch_rules",
        Setpgid => "process_group_syscalls_follow_linux_pid_zero_and_esrch_rules",
        Getuid => "credential_getters_return_current_linux_ids",
        Getgid => "credential_getters_return_current_linux_ids",
        Geteuid => "credential_getters_return_current_linux_ids",
        Getegid => "credential_getters_return_current_linux_ids",
        Setuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setgid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setreuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setregid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setresuid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setresgid => "credential_setters_update_linux_real_effective_saved_and_fs_ids",
        Setfsuid => "fsuid_fsgid_syscalls_return_previous_ids_and_update_state",
        Setfsgid => "fsuid_fsgid_syscalls_return_previous_ids_and_update_state",
        Getgroups => "group_syscalls_validate_linux_size_rules",
        Setgroups => "group_syscalls_validate_linux_size_rules",
        ClockGetres => "clock_getres_accepts_null_for_valid_clocks_and_rejects_bad_clock_ids",
        SchedYield => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Madvise => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Getpriority => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Setpriority => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        IoprioSet => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        IoprioGet => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetscheduler => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetPriorityMax => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        SchedGetPriorityMin => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Iopl => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Ioperm => "scheduler_priority_and_io_permission_syscalls_validate_linux_arguments",
        Gettid => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Getsid => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Setsid => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Umask => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Getresuid => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Getresgid => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Prctl => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        ArchPrctl => "process_session_and_prctl_syscalls_follow_linux_state_rules",
        Capget => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Capset => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        SetTidAddress => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        SetRobustList => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Rseq => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Getrandom => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Time => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Gettimeofday => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Getrusage => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Settimeofday => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Sysinfo => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Alarm => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Sync => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        SchedSetparam => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        SchedGetparam => "misc_state_syscalls_follow_linux_pointer_and_state_rules",
        Uname => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Sethostname => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Reboot => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        SchedRrGetInterval => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Setrlimit => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Getrlimit => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Prlimit64 => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        Vhangup => "uname_reboot_and_rlimit_syscalls_follow_linux_abi_rules",
        ClockGettime => "clock_and_affinity_syscalls_follow_linux_pointer_rules",
        ClockSettime => "clock_and_affinity_syscalls_follow_linux_pointer_rules",
        ClockNanosleep => "clock_and_affinity_syscalls_follow_linux_pointer_rules",
        SchedSetaffinity => "clock_and_affinity_syscalls_follow_linux_pointer_rules",
        SchedGetaffinity => "clock_and_affinity_syscalls_follow_linux_pointer_rules",
        InotifyInit => "inotify_init_syscalls_follow_linux_flag_rules",
        TimerfdCreate => "timerfd_syscalls_follow_linux_flag_and_timer_rules",
        Eventfd => "eventfd_syscalls_follow_linux_flag_rules",
        TimerfdSettime => "timerfd_syscalls_follow_linux_flag_and_timer_rules",
        TimerfdGettime => "timerfd_syscalls_follow_linux_flag_and_timer_rules",
        Eventfd2 => "eventfd_syscalls_follow_linux_flag_rules",
        InotifyInit1 => "inotify_init_syscalls_follow_linux_flag_rules",
        Pipe => "pipe_and_dup_syscalls_follow_linux_fd_rules",
        Dup => "pipe_and_dup_syscalls_follow_linux_fd_rules",
        Dup2 => "pipe_and_dup_syscalls_follow_linux_fd_rules",
        Pipe2 => "pipe_and_dup_syscalls_follow_linux_fd_rules",
        Dup3 => "pipe_and_dup_syscalls_follow_linux_fd_rules",
        Access => "filesystem_path_state_syscalls_follow_linux_rules",
        Getcwd => "filesystem_path_state_syscalls_follow_linux_rules",
        Chdir => "filesystem_path_state_syscalls_follow_linux_rules",
        Chroot => "filesystem_path_state_syscalls_follow_linux_rules",
        PivotRoot => "filesystem_path_state_syscalls_follow_linux_rules",
        Fchdir => "filesystem_path_state_syscalls_follow_linux_rules",
        Faccessat => "filesystem_path_state_syscalls_follow_linux_rules",
        Faccessat2 => "filesystem_path_state_syscalls_follow_linux_rules",
        Link => "filesystem_create_link_syscalls_follow_linux_rules",
        Unlink => "filesystem_create_link_syscalls_follow_linux_rules",
        Symlink => "filesystem_create_link_syscalls_follow_linux_rules",
        Mkdir => "filesystem_create_link_syscalls_follow_linux_rules",
        Rmdir => "filesystem_create_link_syscalls_follow_linux_rules",
        LinkAt => "filesystem_create_link_syscalls_follow_linux_rules",
        SymlinkAt => "filesystem_create_link_syscalls_follow_linux_rules",
        ReadlinkAt => "filesystem_create_link_syscalls_follow_linux_rules",
        UnlinkAt => "filesystem_create_link_syscalls_follow_linux_rules",
        MkdirAt => "filesystem_create_link_syscalls_follow_linux_rules",
        Readlink => "filesystem_create_link_syscalls_follow_linux_rules",
        OpenAt => "filesystem_fd_state_syscalls_follow_linux_rules",
        Open => "filesystem_fd_state_syscalls_follow_linux_rules",
        Creat => "filesystem_fd_state_syscalls_follow_linux_rules",
        Close => "filesystem_fd_state_syscalls_follow_linux_rules",
        Fstat => "filesystem_fd_state_syscalls_follow_linux_rules",
        Lseek => "filesystem_fd_state_syscalls_follow_linux_rules",
        Stat => "filesystem_metadata_syscalls_follow_linux_rules",
        Lstat => "filesystem_metadata_syscalls_follow_linux_rules",
        Chmod => "filesystem_metadata_syscalls_follow_linux_rules",
        Fchmod => "filesystem_metadata_syscalls_follow_linux_rules",
        Newfstatat => "filesystem_metadata_syscalls_follow_linux_rules",
        Fchmodat => "filesystem_metadata_syscalls_follow_linux_rules",
        Fchmodat2 => "filesystem_metadata_syscalls_follow_linux_rules",
        Read => "filesystem_io_syscalls_follow_linux_rules",
        Write => "filesystem_io_syscalls_follow_linux_rules",
        Pread64 => "filesystem_io_syscalls_follow_linux_rules",
        Pwrite64 => "filesystem_io_syscalls_follow_linux_rules",
        Readv => "filesystem_io_syscalls_follow_linux_rules",
        Rename => "filesystem_rename_syscalls_follow_linux_rules",
        RenameAt => "filesystem_rename_syscalls_follow_linux_rules",
        RenameAt2 => "filesystem_rename_syscalls_follow_linux_rules",
        Getdents => "filesystem_getdents_syscalls_follow_linux_rules",
        Getdents64 => "filesystem_getdents_syscalls_follow_linux_rules",
        Writev => "filesystem_file_object_syscalls_follow_linux_rules",
        Fcntl => "filesystem_file_object_syscalls_follow_linux_rules",
        Flock => "filesystem_file_object_syscalls_follow_linux_rules",
        Fsync => "filesystem_file_object_syscalls_follow_linux_rules",
        Fdatasync => "filesystem_file_object_syscalls_follow_linux_rules",
        Ftruncate => "filesystem_file_object_syscalls_follow_linux_rules",
        Fadvise64 => "filesystem_file_object_syscalls_follow_linux_rules",
        Fallocate => "filesystem_file_object_syscalls_follow_linux_rules",
        Sendfile => "filesystem_file_object_syscalls_follow_linux_rules",
        CopyFileRange => "filesystem_file_object_syscalls_follow_linux_rules",
        Splice => "filesystem_file_object_syscalls_follow_linux_rules",
        Chown => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Lchown => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Fchown => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Fchownat => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Mknodat => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Statfs => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Fstatfs => "filesystem_file_metadata_syscalls_follow_linux_rules",
        Setxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Lsetxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Fsetxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Getxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Lgetxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Fgetxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Listxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Llistxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Flistxattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Removexattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Lremovexattr => "filesystem_xattr_syscalls_follow_linux_rules",
        Fremovexattr => "filesystem_xattr_syscalls_follow_linux_rules",
        InotifyAddWatch => "memfd_and_inotify_watch_syscalls_follow_linux_rules",
        InotifyRmWatch => "memfd_and_inotify_watch_syscalls_follow_linux_rules",
        MemfdCreate => "memfd_and_inotify_watch_syscalls_follow_linux_rules",
        EpollWait => "epoll_syscalls_follow_linux_rules",
        EpollCreate => "epoll_syscalls_follow_linux_rules",
        EpollCtl => "epoll_syscalls_follow_linux_rules",
        Unshare => "namespace_and_kcmp_syscalls_follow_linux_rules",
        Utime => "filesystem_utimensat_success_syscalls_follow_linux_rules",
        Utimes => "filesystem_utimensat_success_syscalls_follow_linux_rules",
        Utimensat => "filesystem_utimensat_success_syscalls_follow_linux_rules",
        EpollPwait => "epoll_syscalls_follow_linux_rules",
        Signalfd4 => "signalfd_syscalls_follow_linux_rules",
        EpollCreate1 => "epoll_syscalls_follow_linux_rules",
        NameToHandleAt => "filesystem_name_to_handle_success_syscalls_follow_linux_rules",
        Setns => "namespace_and_kcmp_syscalls_follow_linux_rules",
        Kcmp => "namespace_and_kcmp_syscalls_follow_linux_rules",
        Statx => "filesystem_statx_syscalls_follow_linux_rules",
        Nanosleep => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Select => "select_and_pselect6_syscalls_follow_linux_rules",
        Setitimer => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Getitimer => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        RtSigprocmask => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        RtSigpending => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Pause => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Kill => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Sigaltstack => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        RtSigaction => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        RtSigqueueinfo => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        RtSigtimedwait => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Tkill => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Tgkill => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        Wait4 => "pidfd_and_waitid_syscalls_follow_linux_rules",
        Waitid => "pidfd_and_waitid_syscalls_follow_linux_rules",
        PidfdOpen => "pidfd_and_waitid_syscalls_follow_linux_process_rules",
        PidfdSendSignal => "pidfd_and_waitid_syscalls_follow_linux_rules",
        CloseRange => "close_range_syscalls_follow_linux_rules",
        RtSigsuspend => "sleep_and_signal_mask_syscalls_follow_linux_rules",
        EpollPwait2 => "epoll_pwait2_syscalls_follow_linux_timeout_rules",
        QuotactlFd => "quotactl_fd_syscalls_follow_linux_rules",
        Poll => "poll_and_ppoll_syscalls_follow_linux_rules",
        Ppoll => "poll_and_ppoll_syscalls_follow_linux_rules",
        TimerCreate => "posix_timer_syscalls_follow_linux_rules",
        TimerSettime => "posix_timer_syscalls_follow_linux_rules",
        TimerGettime => "posix_timer_syscalls_follow_linux_rules",
        TimerGetoverrun => "posix_timer_syscalls_follow_linux_rules",
        TimerDelete => "posix_timer_syscalls_follow_linux_rules",
        Pselect6 => "pselect6_syscalls_follow_linux_rules",
        Shutdown => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Getsockname => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Getpeername => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Socketpair => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Socket => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Setsockopt => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Getsockopt => "socket_name_and_shutdown_syscalls_follow_linux_rules",
        Connect => "socket_bind_connect_accept_syscalls_follow_linux_rules",
        Accept4 => "socket_bind_connect_accept_syscalls_follow_linux_rules",
        Bind => "socket_bind_connect_accept_syscalls_follow_linux_rules",
        Listen => "socket_bind_connect_accept_syscalls_follow_linux_rules",
        Accept => "socket_message_syscalls_follow_linux_rules",
        Sendmsg => "socket_message_syscalls_follow_linux_rules",
        Sendmmsg => "socket_message_syscalls_follow_linux_rules",
        Sendto => "socket_message_syscalls_follow_linux_rules",
        Recvfrom => "socket_message_syscalls_follow_linux_rules",
        Recvmsg => "socket_message_syscalls_follow_linux_rules",
        Brk => "memory_mapping_syscalls_follow_linux_rules",
        Mmap => "memory_mapping_syscalls_follow_linux_rules",
        Mprotect => "memory_mapping_syscalls_follow_linux_rules",
        Munmap => "memory_mapping_syscalls_follow_linux_rules",
        Mremap => "memory_mapping_syscalls_follow_linux_rules",
        Msync => "memory_mapping_syscalls_follow_linux_rules",
        Mincore => "memory_mapping_syscalls_follow_linux_rules",
        Mlock => "memory_mapping_syscalls_follow_linux_rules",
        Munlock => "memory_mapping_syscalls_follow_linux_rules",
        GetMempolicy => "memory_mapping_syscalls_follow_linux_rules",
        Shmget => "sysv_shm_syscalls_follow_linux_rules",
        Shmat => "sysv_shm_syscalls_follow_linux_rules",
        Shmctl => "sysv_shm_syscalls_follow_linux_rules",
        Shmdt => "sysv_shm_syscalls_follow_linux_rules",
        Semget => "sysv_sem_syscalls_follow_linux_rules",
        Semop => "sysv_sem_syscalls_follow_linux_rules",
        Semtimedop => "sysv_sem_syscalls_follow_linux_rules",
        Semctl => "sysv_sem_syscalls_follow_linux_rules",
        Msgget => "sysv_msg_syscalls_follow_linux_rules",
        Msgsnd => "sysv_msg_syscalls_follow_linux_rules",
        Msgrcv => "sysv_msg_syscalls_follow_linux_rules",
        Msgctl => "sysv_msg_syscalls_follow_linux_rules",
        AddKey => "key_and_bpf_syscalls_follow_linux_rules",
        Keyctl => "key_and_bpf_syscalls_follow_linux_rules",
        Bpf => "key_and_bpf_syscalls_follow_linux_rules",
        Ioctl => "object_control_syscalls_follow_linux_rules",
        RtSigreturn => "process_and_signal_transition_helpers_follow_linux_rules",
        SchedSetscheduler => "object_control_syscalls_follow_linux_rules",
        Mount => "mount_api_syscalls_follow_linux_rules",
        Umount2 => "mount_api_syscalls_follow_linux_rules",
        OpenTree => "mount_api_syscalls_follow_linux_rules",
        MoveMount => "mount_api_syscalls_follow_linux_rules",
        Fsopen => "mount_api_syscalls_follow_linux_rules",
        Fsconfig => "mount_api_syscalls_follow_linux_rules",
        Fsmount => "mount_api_syscalls_follow_linux_rules",
        MountSetattr => "mount_api_syscalls_follow_linux_rules",
        Ptrace => "ptrace_syscalls_follow_linux_rules",
        Clone => "clone_and_fork_syscalls_follow_linux_rules",
        Fork => "clone_and_fork_syscalls_follow_linux_rules",
        Vfork => "clone_and_fork_syscalls_follow_linux_rules",
        Clone3 => "clone_and_fork_syscalls_follow_linux_rules",
        Futex => "futex_syscalls_follow_linux_rules",
        IoSetup => "aio_context_syscalls_follow_linux_lifecycle_rules",
        IoDestroy => "aio_context_syscalls_follow_linux_lifecycle_rules",
        IoGetevents => "aio_context_syscalls_follow_linux_lifecycle_rules",
        IoSubmit => "aio_context_syscalls_follow_linux_lifecycle_rules",
        IoCancel => "aio_context_syscalls_follow_linux_lifecycle_rules",
        Execve => "execve_syscalls_follow_linux_rules",
        Execveat => "execve_syscalls_follow_linux_rules",
        Exit => "exit_thread_semantics_follow_linux_rules",
        ExitGroup => "exit_group_semantics_follow_linux_rules",
    }
    gap {
    }
);
