use crate::register_syscalls;
use crate::systemcall::implementations::*;
use crate::systemcall::utils::SyscallImpl;
use crate::systemcall::utils::SyscallResult;

type SyscallHandler = fn(u64, u64, u64, u64, u64, u64) -> SyscallResult;

pub static SYSCALL_TABLE: [Option<SyscallHandler>; 1500] = {
    let mut table = [None; 1500];

    register_syscalls!(
        table,
        Read,
        Write,
        OpenAt,
        Close,
        Fstat,
        Lseek,
        Mmap,
        Mprotect,
        Munmap,
        Brk,
        RtSigaction,
        RtSigprocmask,
        RtSigreturn,
        Ioctl,
        Pread64,
        Pwrite64,
        Access,
        SchedYield,
        Dup,
        Nanosleep,
        Socket,
        Connect,
        Accept,
        Recvmsg,
        Shutdown,
        Bind,
        Listen,
        Getsockname,
        Getpeername,
        Getsockopt,
        Clone,
        Fork,
        Execve,
        Exit,
        Wait4,
        Kill,
        Uname,
        Fcntl,
        Flock,
        Fsync,
        Fdatasync,
        Ftruncate,
        Getdents,
        Getcwd,
        Chdir,
        Readlink,
        Getpid,
        Getppid,
        Setpgid,
        Getpgid,
        Setsid,
        ArchPrctl,
        Gettid,
        Futex,
        EpollWait,
        EpollCtl,
        ClockGettime,
        MkdirAt,
        Newfstatat,
        UnlinkAt,
        RenameAt,
        LinkAt,
        ReadlinkAt,
        Faccessat,
        Utimensat,
        EpollPwait,
        Fallocate,
        Dup3,
        EpollCreate1,
        Getpriority,
        Setrlimit,
        Sync,
        RenameAt2,
        TimerCreate,
        TimerSettime,
        TimerGettime,
        TimerGetoverrun,
        TimerDelete
    );

    table
};
