pub enum AuxType {
    Null = 0,
    Ignore = 1,
    Flags = 8,
    NotElf = 10,
    UserId = 11,
    EffectiveUserId = 12,
    GroupId = 13,
    EffectiveGroupId = 14,
    Platform = 15,
    HardwareCapabilities = 16,
    ClockTick = 17,
    Secure = 23,
    Random = 25,
    ExecFilename = 31,
    BaseAddress = 7,
    ProgramHeaderTable = 3,
    ProgramHeaderEntrySize = 4,
    ProgramHeaderAmount = 5,
    PageSize = 6,
    EntryPointAddress = 9,
}
