[unstable]
bindeps = true
unstable-options = true

[target.x86_64-unknown-none]
rustflags = [
  "-C", "relocation-model=static",
]

[alias]
xrun = "run -p xtask -- run"
xtest = "run -q -p xtask -- test"
xbuild-rootfs = "run -p xtask -- build-rootfs"
