[unstable]
bindeps = true
unstable-options = true

[target.x86_64-unknown-none]
rustflags = [
  "-C", "relocation-model=static",
]

[alias]
xrun = "run -p control-cli -- run"
xtest = "run -q -p control-cli -- test"
xbuild-rootfs = "run -p control-cli -- rootfs"
