[General]
GreeterEnvironment=QT_QUICK_BACKEND=software,QSG_RHI_BACKEND=software,QT_XCB_FORCE_SOFTWARE_OPENGL=1,QT_OPENGL=software,LIBGL_ALWAYS_SOFTWARE=1,LANG=C.UTF-8,LC_ALL=C.UTF-8

[Theme]
Current=breeze
