#!/bin/sh

set -eu

uid="$(id -u)"
runtime_dir="${XDG_RUNTIME_DIR:-/run/user/${uid}}"
display_name="${WAYLAND_DISPLAY:-wayland-0}"
display_socket="${runtime_dir}/${display_name}"

# startplasma may D-Bus-activate KSplash before kwin has created the socket.
while [ ! -S "${display_socket}" ]; do
    sleep 0.1
done

export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-wayland}"
exec /usr/bin/ksplashqml
