[options]
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Never

[core]
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch

[extra]
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
