mod accept;
mod bind;
mod connect;
mod create;
mod drop_impl;
mod error;
mod object;
mod registry;
mod sockopt;
mod state;
mod stream;
mod traits_object;
mod traits_poll;
mod traits_read;
mod traits_write;
mod wake;

pub use error::{SocketError, SocketResult};
pub use object::UnixSocketObject;
pub(crate) use registry::UNIX_SOCKET_REGISTRY;
pub use state::{UnixListenerInner, UnixSocketState};
pub use stream::{SocketPeerCred, UnixStreamInner};
pub(crate) use wake::{wake_io, wake_pollers};
