mod accept;
mod bind;
mod connect;
mod create;
mod datagram;
mod drop_impl;
mod error;
mod name;
mod object;
mod pair;
mod registry;
mod sockopt;
mod state;
mod stream;
mod traits_object;
mod traits_poll;
mod traits_read;
mod traits_stat;
mod traits_write;
mod wake;

pub const AF_UNIX: u64 = 1;
pub const SOL_SOCKET: u64 = 1;
pub const SOCK_STREAM: u64 = 1;
pub const SOCK_DGRAM: u64 = 2;
pub const SOCK_SEQPACKET: u64 = 5;
pub const SOCK_NONBLOCK: u64 = 0o4_000;
pub const SOCK_CLOEXEC: u64 = 0o2_000_000;
pub const SO_REUSEADDR: u64 = 2;
pub const SO_TYPE: u64 = 3;
pub const SO_ERROR: u64 = 4;
pub const SO_SNDBUF: u64 = 7;
pub const SO_RCVBUF: u64 = 8;
pub const SO_PASSCRED: u64 = 16;
pub const SO_PEERCRED: u64 = 17;
pub const SO_ACCEPTCONN: u64 = 30;
pub const SO_PROTOCOL: u64 = 38;
pub const SO_DOMAIN: u64 = 39;

pub use datagram::{DATAGRAM_RECV_CAPACITY, UnixDatagramInner, UnixDatagramMessage};
pub use error::{SocketError, SocketResult};
pub use object::{UnixSocketKind, UnixSocketObject};
pub(crate) use registry::{UNIX_SOCKET_REGISTRY, UnixSocketRegistryEntry};
pub use state::{UnixListenerInner, UnixSocketState};
pub use stream::{STREAM_RECV_CAPACITY, SocketPeerCred, UnixStreamInner};
pub(crate) use wake::{wake_io, wake_pollers};
